### PR TITLE
Create How-to-Filter-Programmers.md

### PR DESCRIPTION
**Pull request by jak234**

### CODE REVIEW

**Comment by ktasandvold** [comment]
Please add an image and link as per the assignment text. 
 "Make sure to include at least one link and one image, so you'll have to learn the basics of "GitHub flavored markdown". Please see the below link for examples of how to do that:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by Einos315** [comment]
Once you add in a link and image, I think this is good to go. Very thoughtful and thorough considerations you've included here! :+1:

**Comment by pritirao** [comment]
Consider adding - "One way to filter programmers is to get recommendations from current developers."

**Comment by jak234** [comment]
Added link and image as per @ktasandvold feedback and added line suggested from @pritirao. Thanks for your input @Einos315!

**Comment by pritirao** [comment]
Thanks for updating @jak234! :+1: to ship from me

**Comment by ktasandvold** [comment]
Thanks for updating @jak234  :+1: to ship from me

**Comment by ktasandvold** [comment]
asking for a :+1: to ship

**Comment by ktasandvold** [comment]
Sorry. Not sure what I was doing with the closing and reopening. What I meant to say is :+1: to ship from me.

**Comment by marcuscbs** [comment]
:+1: to ship from me! Looks good to go

**Pull request merged**
