### PR TITLE
Incremental-Software-Development

### PR DESCRIPTION
**Pull request by ktasandvold**

### CODE REVIEW

**Comment by pritirao** [comment]
Hey! So file appears blank when I tried to look at it. Perhaps try uploading it again?

**Comment by ktasandvold** [comment]
Thank you @pritirao 
The file should include content now

**Comment by pritirao** [comment]
Consider adding under BDU - "BDU also requires upfront planning including budgets and project timelines, which can cost money and waste valuable developer time."

**Comment by ktasandvold** [comment]
Added "BDU also requires upfront planning including budgets and project timelines, which can cost money and waste valuable developer time." as per @pritirao  comment.

**Comment by ktasandvold** [comment]
Thank you to @pritirao for the quick feedback. Please can @jak234 @Einos315 and @marcuscbs also provide some feedback so that I can improve my file?

**Comment by Einos315** [comment]
Looks good. Consider adding: Test-driven development can also be a key part of incremental software development -- the two can be integrated.

Otherwise, :+1:

**Comment by pritirao** [comment]
Thanks for updating with my comments @ktasandvold. It's :+1: from me!

**Comment by marcuscbs** [comment]
Consider adding: Needs complete definition of the whole system before it can be broken down and built incrementally.

**Comment by ktasandvold** [comment]
Thanks to @pritirao and @Einos315 for :+1: to ship. I will merge the PR now. Thanks to @marcuscbs and @jak234 for your feedback

**Pull request merged**
