### PR TITLE
Lessons Learned from Pragmatic Programmer - Added files via upload

### PR DESCRIPTION
**Pull request by pritirao**
Please find my notes on pragmatic programmer.

### CODE REVIEW

**Comment by marcuscbs** [comment]
Consider adding test your software for bugs frequently and once you identify one create automatic tests to check for them in the future.

**Comment by ktasandvold** [comment]
Please add an image and link as per the assignment text. 
"Make sure to include at least one link and one image, so you'll have to learn the basics of "GitHub flavored markdown". "

**Comment by pritirao** [comment]
Updated with @marcuscbs and @ktasandvold comments. Please add comments @Einos315 @jak234 so I can improve my file.

**Comment by pritirao** [comment]
Thanks @jak234! Updated with your edits

**Comment by jak234** [comment]
Thanks for updating @pritirao! :thumbsup:

**Comment by Einos315** [comment]
Consider adding in the idea of reversibility -- it is critical to plan ahead with contingencies, and to think of critical decisions as being written in the sand instead of carved in stone.

Otherwise, :+1:

**Comment by pritirao** [comment]
Thank you @Einos315! Updated with your comments. Thanks @marcuscbs @ktasandvold @jak234 for your helpful feedback!

**Pull request merged**
