### PR TITLE
Adding Mobile App vs. Website

### PR DESCRIPTION
**Pull request by marcuscbs**

### CODE REVIEW

**Comment by pritirao** [comment]
Consider adding - "Mobile apps have to be created for iOS and Android independently. Mobile sites can be used on any device."

**Comment by marcuscbs** [comment]
@ktasandvold thanks for the comment. will add an image now!

**Comment by pritirao** [comment]
Looks great! :+1: to ship

**Comment by ktasandvold** [comment]
:+1: to ship

**Comment by marcuscbs** [comment]
:+1: to ship from me. Thanks for feedback!

**Pull request merged**
